### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by Bizarrus** [patrykcieszkowski/node-bbcode#1]
Please tell us better samples.

How `allowData` will be used? Array? Split comma seperated?

I won't search the source each time for each NPM-Plugin to find the answer. Please update yor "Documentation" with better examples!

**Comment by patrykcieszkowski** [comment]
@Bizarrus hi! I thought it's quite clear, those are boolean values, as it;s described.

![image](https://cloud.githubusercontent.com/assets/16166259/26409179/ba8f2368-4097-11e7-88ab-e7e3926bb574.png)

But you're right, maybe it needs better form of description. Will update with more samples soon. Thanks!

**Comment by patrykcieszkowski** [comment]
#issuecomment-303745952
